-- AlterTable
ALTER TABLE "Holding" ALTER COLUMN "ticker" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(255);

-- AlterTable
ALTER TABLE "HoldingHistory" ALTER COLUMN "ticker" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(255);
